name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Check files
      run: ls -la && cat buildozer.spec | head -5
    - name: Build
      run: |
        pip install buildozer==1.5.0 cython==0.29.36
        sudo apt-get install -y openjdk-17-jdk zip unzip
        yes | buildozer android debug
    - name: Upload
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: APK
        path: bin/*.apk
